using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RequireJsNet
{
    public class RequireRendererConfiguration
    {
        private string baseUrl = string.Empty;

        private string requireJsUrl = string.Empty;

        private string urlArgs = null;

        private string entryPointRoot = "~/Scripts/";

        private bool loadOverrides = true;

        private IList<string> configPaths = new[] { "~/RequireJS.config" };

        /// <summary>
        /// Scripts base url
        /// </summary>
        public string BaseUrl
        {
            get
            {
                return baseUrl;
            }

            set
            {
                baseUrl = value;
            }
        }

        /// <summary>
        /// RequireJS javascript file url
        /// </summary>
        public string RequireJsUrl
        {
            get
            {
                return this.requireJsUrl;
            }

            set
            {
                this.requireJsUrl = value;
            }
        }

        /// <summary>
        /// Value passed to the urlArgs setting of RequireJS
        /// </summary>
        public string UrlArgs
        {
            get
            {
                return urlArgs;
            }

            set
            {
                urlArgs = value;
            }
        }

        /// <summary>
        /// List of RequireJS config file paths
        /// </summary>
        public IList<string> ConfigurationFiles
        {
            get
            {
                return configPaths;
            }

            set
            {
                configPaths = value;
            }
        }

        /// <summary>
        /// Scripts folder relative path (ex. ~/Scripts/)
        /// </summary>
        public string EntryPointRoot
        {
            get
            {
                return entryPointRoot;
            }

            set
            {
                entryPointRoot = value;
            }
        }

        /// <summary>
        /// Logger for library output
        /// </summary>
        public IRequireJsLogger Logger { get; set; }


        /// <summary>
        /// A value indicating whether overrides generated by the AutoCompressor shoudl eb loaded.
        /// </summary>
        public bool LoadOverrides
        {
            get
            {
                return loadOverrides;
            }

            set
            {
                loadOverrides = value;
            }
        }
    }
}
